"""Recommendation engine: versioned playbook catalogue + decision-theoretic scoring.

Recommendations are never generated by a model.  They are selected from a
catalogue an accountable human owns, and the model at most phrases them.

Two rules that matter more than the arithmetic:

  1. THE LICENSED ACTION TYPE IS A HARD FILTER.  The materiality engine decides
     whether the evidence licenses REMEDIATE, INVESTIGATE or MONITOR.  A remedial
     playbook cannot surface against an unidentified hypothesis no matter how
     large the exposure, because spending money to fix an unestablished mechanism
     is a gamble, not a decision.  The engine offers INVESTIGATE actions instead:
     buying information is the correct response to a big unidentified number.

  2. THE IDENTIFICATION CAP IS A CEILING, NOT A MULTIPLIER.  V4 said the cap was
     a max() and then implemented a product.  Here the benefit term is
     min(impact, cap): a high-impact action attached to weak identification
     cannot outscore a modest action attached to a solid one.

Persona changes which playbooks are visible and how they are framed - an
operations manager gets capacity actions at warehouse level, a CFO gets exposure
and disclosure actions.  Neither sees the other's.
"""
from __future__ import annotations

from dataclasses import dataclass, field, asdict

CATALOGUE_VERSION = "playbooks-v5.0.2"

IDENTIFICATION_CAP = {
    "SUPPORTED_BY_INTERVENTION": 0.90,
    "SUPPORTED_BY_DESIGN": 0.85,
    "NOT_POINT_IDENTIFIED": 0.45,
    "ASSOCIATION_ONLY": 0.25,
    "INSUFFICIENT_EVIDENCE": 0.15,
}


@dataclass(frozen=True)
class Playbook:
    playbook_id: str
    title: str
    targets_driver: str
    action_type: str                 # REMEDIATE | INVESTIGATE | MONITOR
    personas: tuple[str, ...]
    impact_index: float              # 0..1 expected relative recovery if mechanism holds
    direct_cost_index: float         # 0..1
    effort_index: float              # 0..1
    opportunity_cost_index: float    # 0..1
    irreversibility: float           # 0..1
    downside_exposure: float         # 0..1
    time_to_impact_days: tuple[int, int]
    resource_dimension: str          # for cross-recommendation conflict detection
    cost_band: str
    owner: str
    framing: dict                    # persona_id -> framing sentence
    evidence_requirements: tuple[str, ...] = ()


PLAYBOOKS: tuple[Playbook, ...] = (
    Playbook(
        playbook_id="PB-OPS-001",
        title="Activate contracted overflow 3PL capacity for the North distribution centres",
        targets_driver="on_time_dispatch_rate", action_type="REMEDIATE",
        personas=("ops_manager", "cfo", "finance_analyst"),
        impact_index=0.72, direct_cost_index=0.45, effort_index=0.30,
        opportunity_cost_index=0.20, irreversibility=0.15, downside_exposure=0.20,
        time_to_impact_days=(7, 14), resource_dimension="logistics_spend",
        cost_band="MEDIUM", owner="fulfilment.ops@northwind.example",
        framing={
            "ops_manager": ("Raise the 3PL overflow lane for WH-N1 and WH-N2 to clear the "
                            "dispatch backlog; the SLA breach is concentrated there."),
            "cfo": ("Incremental logistics spend against a quantified revenue exposure; "
                    "reversible within one billing cycle."),
            "finance_analyst": ("Model this as incremental COGS with a 7 to 14 day lag to "
                                "revenue recovery; tag for post-intervention validation."),
        },
        evidence_requirements=("identified dispatch effect", "warehouse-level SLA breach")),
    Playbook(
        playbook_id="PB-OPS-002",
        title="Re-sequence the dispatch queue to prioritise aged orders",
        targets_driver="on_time_dispatch_rate", action_type="REMEDIATE",
        personas=("ops_manager",),
        impact_index=0.34, direct_cost_index=0.05, effort_index=0.20,
        opportunity_cost_index=0.10, irreversibility=0.05, downside_exposure=0.10,
        time_to_impact_days=(1, 3), resource_dimension="warehouse_labour",
        cost_band="LOW", owner="fulfilment.ops@northwind.example",
        framing={"ops_manager": ("Zero-cost sequencing change; clears the oldest orders "
                                 "first and cuts the late-delivery ticket inflow.")}),
    Playbook(
        playbook_id="PB-CX-001",
        title="Proactive delivery-delay outreach to affected customers",
        targets_driver="complaint_rate", action_type="REMEDIATE",
        personas=("ops_manager", "cfo"),
        impact_index=0.28, direct_cost_index=0.12, effort_index=0.25,
        opportunity_cost_index=0.10, irreversibility=0.05, downside_exposure=0.15,
        time_to_impact_days=(3, 7), resource_dimension="cx_capacity",
        cost_band="LOW", owner="customer.experience@northwind.example",
        framing={
            "ops_manager": ("Notify customers whose orders breached SLA before they open "
                            "a ticket; reduces inbound volume within a week."),
            "cfo": "Low-cost retention action; limits refund and churn leakage."}),
    Playbook(
        playbook_id="PB-COM-001",
        title="Commission a competitor promotion intensity read for the affected window",
        targets_driver="competitor_promo", action_type="INVESTIGATE",
        personas=("cfo", "finance_analyst"),
        impact_index=0.55, direct_cost_index=0.18, effort_index=0.15,
        opportunity_cost_index=0.05, irreversibility=0.02, downside_exposure=0.05,
        time_to_impact_days=(10, 21), resource_dimension="insights_budget",
        cost_band="LOW", owner="commercial.insights@northwind.example",
        framing={
            "cfo": ("The exposure attached to competitor activity is material but not "
                    "identified. Buying a discount-depth read is the cheapest way to "
                    "convert an unknown into a decision."),
            "finance_analyst": ("Procuring promotion intensity would open a backdoor "
                                "adjustment set and make this effect estimable.")}),
    Playbook(
        playbook_id="PB-MKT-001",
        title="Onboard Region South to CampaignHub and backfill campaign timing",
        targets_driver="marketing_spend", action_type="INVESTIGATE",
        personas=("cfo", "finance_analyst", "ops_manager"),
        impact_index=0.40, direct_cost_index=0.10, effort_index=0.35,
        opportunity_cost_index=0.05, irreversibility=0.05, downside_exposure=0.05,
        time_to_impact_days=(14, 30), resource_dimension="data_platform",
        cost_band="LOW", owner="marketing.ops@northwind.example",
        framing={
            "cfo": ("A whole region is invisible to marketing attribution. This is a "
                    "reporting-integrity gap, not an analysis preference."),
            "finance_analyst": ("Removes an unavailable-variable blocker that currently "
                                "forces abstention on every South-region analysis."),
            "ops_manager": ("South campaign timing is missing, which is why no marketing "
                            "driver appears in South analyses.")}),
    Playbook(
        playbook_id="PB-MKT-002",
        title="Request daily-grain marketing spend delivery from CampaignHub",
        targets_driver="marketing_spend", action_type="INVESTIGATE",
        personas=("finance_analyst", "cfo"),
        impact_index=0.32, direct_cost_index=0.08, effort_index=0.30,
        opportunity_cost_index=0.05, irreversibility=0.05, downside_exposure=0.05,
        time_to_impact_days=(21, 45), resource_dimension="data_platform",
        cost_band="LOW", owner="marketing.ops@northwind.example",
        framing={
            "finance_analyst": ("Weekly grain makes any lag shorter than seven days "
                                "unmeasurable; daily delivery is the only fix."),
            "cfo": "Structural fix so marketing can be assessed at all in future cycles."}),
    Playbook(
        playbook_id="PB-PRC-001",
        title="Review realised-price erosion from defensive discounting",
        targets_driver="avg_selling_price", action_type="INVESTIGATE",
        personas=("cfo", "finance_analyst"),
        impact_index=0.38, direct_cost_index=0.05, effort_index=0.20,
        opportunity_cost_index=0.15, irreversibility=0.10, downside_exposure=0.25,
        time_to_impact_days=(7, 21), resource_dimension="pricing_policy",
        cost_band="LOW", owner="pricing@northwind.example",
        framing={
            "cfo": ("Realised price fell even though list price rose. The gap is discount "
                    "depth and mix, and both are policy levers."),
            "finance_analyst": ("Separate the list-price action from discount drift before "
                                "revising the price-volume forecast.")}),
    Playbook(
        playbook_id="PB-GOV-001",
        title="Hold the analysis window open and re-run when the stale feed refreshes",
        targets_driver="*", action_type="MONITOR",
        personas=("cfo", "finance_analyst", "ops_manager"),
        impact_index=0.15, direct_cost_index=0.01, effort_index=0.05,
        opportunity_cost_index=0.02, irreversibility=0.00, downside_exposure=0.02,
        time_to_impact_days=(2, 7), resource_dimension="analyst_time",
        cost_band="NEGLIGIBLE", owner="analytics.governance@northwind.example",
        framing={
            "cfo": "Defer the decision rather than act on a stale input.",
            "finance_analyst": "Re-run once SRC_MKT lands; keep the current run for audit.",
            "ops_manager": "No operational action; watch the daily SLA trend."}),
    Playbook(
        playbook_id="PB-GOV-002",
        title="Schedule the causal read for the newly launched KPI once history qualifies",
        targets_driver="*", action_type="MONITOR",
        personas=("cfo", "finance_analyst"),
        impact_index=0.12, direct_cost_index=0.01, effort_index=0.05,
        opportunity_cost_index=0.02, irreversibility=0.00, downside_exposure=0.02,
        time_to_impact_days=(14, 40), resource_dimension="analyst_time",
        cost_band="NEGLIGIBLE", owner="analytics.governance@northwind.example",
        framing={
            "cfo": "Accept a descriptive read now; a causal read is not available yet.",
            "finance_analyst": ("Book the re-run for the first date the design becomes "
                                "eligible rather than estimating on short history.")}),
)


@dataclass
class Recommendation:
    recommendation_id: str
    playbook_id: str
    title: str
    action_type: str
    targets_hypothesis: str
    targets_driver: str
    score: float
    score_components: dict
    identification_cap: float
    cost_band: str
    reversibility: str
    time_to_impact_days: list[int]
    resource_dimension: str
    owner: str
    persona_framing: str
    conditional_on: list[str]
    conflicts_with: list[str] = field(default_factory=list)
    catalogue_version: str = CATALOGUE_VERSION

    def as_dict(self) -> dict:
        return asdict(self)


class RecommendationEngine:
    def recommend(self, *, hypotheses: list[dict], materiality: dict[str, dict],
                  persona_id: str, top_n: int = 3) -> list[Recommendation]:
        out: list[Recommendation] = []
        for h in hypotheses:
            hid = h["hypothesis_id"]
            mat = materiality.get(hid) or {}
            licensed = mat.get("action_type", "NO_ACTION")
            if licensed == "NO_ACTION":
                continue
            allowed_types = {
                "REMEDIATE": {"REMEDIATE"},
                "REMEDIATE_WITH_MONITORING": {"REMEDIATE", "MONITOR"},
                "INVESTIGATE": {"INVESTIGATE", "MONITOR"},
                "MONITOR": {"MONITOR"},
            }.get(licensed, {"MONITOR"})
            cap = IDENTIFICATION_CAP.get(h["causal_status"], 0.15)
            for pb in PLAYBOOKS:
                if persona_id not in pb.personas:
                    continue
                if pb.action_type not in allowed_types:
                    continue
                if pb.targets_driver not in ("*", h["driver_id"]):
                    continue
                benefit = min(pb.impact_index, cap)          # CEILING, not a multiplier
                cost = (pb.direct_cost_index + pb.effort_index +
                        pb.opportunity_cost_index) / 3.0
                risk = pb.irreversibility * pb.downside_exposure
                score = benefit - cost - risk
                comps = {
                    "impact_index": pb.impact_index,
                    "identification_cap": cap,
                    "expected_benefit": round(benefit, 4),
                    "benefit_rule": ("min(impact_index, identification_cap) - the cap is "
                                     "a ceiling, so weak identification cannot be "
                                     "outvoted by a large impact index"),
                    "expected_cost": round(cost, 4),
                    "cost_rule": "mean(direct_cost, effort, opportunity_cost)",
                    "risk_penalty": round(risk, 4),
                    "risk_rule": "irreversibility x downside_exposure",
                    "licensed_action_type": licensed,
                    "materiality_priority": mat.get("decision_priority"),
                    "time_to_impact_reported_separately": list(pb.time_to_impact_days),
                }
                out.append(Recommendation(
                    recommendation_id=f"REC-{hid}-{pb.playbook_id}",
                    playbook_id=pb.playbook_id, title=pb.title,
                    action_type=pb.action_type, targets_hypothesis=hid,
                    targets_driver=pb.targets_driver, score=round(score, 4),
                    score_components=comps, identification_cap=cap,
                    cost_band=pb.cost_band,
                    reversibility=("HIGH" if pb.irreversibility < 0.1 else
                                   "MEDIUM" if pb.irreversibility < 0.3 else "LOW"),
                    time_to_impact_days=list(pb.time_to_impact_days),
                    resource_dimension=pb.resource_dimension, owner=pb.owner,
                    persona_framing=pb.framing.get(persona_id, ""),
                    conditional_on=list(pb.evidence_requirements)))

        out.sort(key=lambda r: -r.score)
        out = out[:top_n]
        self._flag_conflicts(out)
        return out

    @staticmethod
    def _flag_conflicts(recs: list[Recommendation]) -> None:
        by_dim: dict[str, list[Recommendation]] = {}
        for r in recs:
            by_dim.setdefault(r.resource_dimension, []).append(r)
        for dim, group in by_dim.items():
            if len(group) > 1:
                for r in group:
                    r.conflicts_with = [o.recommendation_id for o in group
                                        if o.recommendation_id != r.recommendation_id]

    @staticmethod
    def catalogue() -> list[dict]:
        return [{"playbook_id": p.playbook_id, "title": p.title,
                 "action_type": p.action_type, "targets_driver": p.targets_driver,
                 "personas": list(p.personas), "owner": p.owner,
                 "cost_band": p.cost_band,
                 "time_to_impact_days": list(p.time_to_impact_days)}
                for p in PLAYBOOKS]
